apiVersion: v1
kind: Pod
metadata:
  name: mjpg-streamer
  labels:
    app: mjpg-streamer
spec:
  containers:
    - name: mjpg-streamer
      image: fufuhu/mjpg-streamer:docker-meetup
      imagePullPolicy: Always
      securityContext:
        privileged: true
      ports:
      - containerPort: 8080
      volumeMounts:
      - mountPath: /mnt/video0
        name: volume-device
  volumes:
  - name: volume-device
    hostPath:
      path: /dev/video0